<?php

namespace Tests\Unit;

use App\Rectangle;
use http\Exception\InvalidArgumentException;
use PHPUnit\Framework\TestCase;

class RectangleTest extends TestCase {

    public $rectangle;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->rectangle = new Rectangle(2,3);
    }


    /** @test */
    public function accepts_only_numeric_values_for_the_height_and_width()
    {
        $this->expectException("InvalidArgumentException");
        new Rectangle(2, 'test');
    }


    /** @test */
    public function can_set_the_name()
    {
        $this->rectangle->setName('nome');
        $this->assertEquals('nome', $this->rectangle->getName());
    }

    /** @test */
    public function can_get_the_shape_type()
    {
        $this->assertEquals(2, Rectangle::shapeType());
        $this->assertEquals(2, Rectangle::SHAPE_TYPE);
    }

    /** @test */
    public function can_generate_a_new_object_with_the_same_properties()
    {
        $this->rectangle->setName('nome');
        $new_rectangle = $this->rectangle->getObject();
        $this->rectangle->setName('test');

        $this->assertEquals('test', $this->rectangle->getName());
        $this->assertNotEquals('test', $new_rectangle->getName());
    }

    /** @test */
    public function can_return_a_standart_object_with_the_properties()
    {
        $new_object = $this->rectangle->getStandartObject();
        $this->assertEquals(2, $new_object->width);
        $this->assertEquals(3, $new_object->height);
    }

    /** @test */
    public function area_calculation()
    {
        $this->assertEquals(6, $this->rectangle->area());
        $this->assertEquals(10, (new Rectangle(5,2))->area());
    }





}
