<?php

namespace Tests\Unit;

use App\Rectangle;
use http\Exception\InvalidArgumentException;
use PHPUnit\Framework\TestCase;

class RectangleTest extends TestCase {

    public $shape;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->shape = new Rectangle(2,3);
    }


    /** @test */
    public function accepts_only_numeric_values_for_the_height_and_width()
    {
        $this->expectException("InvalidArgumentException");
        new Rectangle(2, 'test');
    }


    /** @test */
    public function can_set_the_name()
    {
        $this->shape->setName('nome');
        $this->assertEquals('nome', $this->shape->getName());
    }

    /** @test */
    public function can_get_the_shape_type()
    {
        $this->assertEquals(2, Rectangle::shapeType());
        $this->assertEquals(2, Rectangle::SHAPE_TYPE);
    }

    /** @test */
    public function can_generate_a_new_object_with_the_same_properties()
    {
        $this->shape->setName('nome');
        $new_shape = $this->shape->getObject();
        $this->shape->setName('test');

        $this->assertEquals('test', $this->shape->getName());
        $this->assertNotEquals('test', $new_shape->getName());
    }

    /** @test */
    public function the_area_must_be_calculated()
    {
        $this->assertEquals(6, $this->shape->area());
        $this->assertEquals(10, (new Rectangle(5,2))->area());
    }





}
